apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ingress-nginx-coordinator
  namespace: kube-system
  labels:
    app: ingress-nginx
spec:
  template:
    metadata:
      labels:
        tier: node
        app: ingress-nginx-coordinator
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: ingress-nginx-coordinator
        image: netmarkjp/k8s-ingress-nginx-coordinator:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: PATH_TO_KUBE_CONFIG
          value: /mnt/kubeconfig/admin.conf
        volumeMounts:
        - name: kubeconfig
          mountPath: "/mnt/kubeconfig"
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
          items:
          - key: kubeconfig
            path: admin.conf
